import tkinter as tk
from tkinter import ttk
import json
import os
from datetime import datetime
from config import Config

class ReportHistoryManager:
    """Manages the history of generated reports (PDFs, Excel exports)."""
    FILE_PATH = os.path.join(Config.BASE_DIR, "report_history.json")
    
    @classmethod
    def log_report(cls, report_type, filename, username, status="Success"):
        history = cls._load_history()
        history.insert(0, {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "type": report_type,
            "filename": os.path.basename(filename),
            "username": username,
            "status": status
        })
        
        if len(history) > 200:
            history = history[:200]
            
        cls._save_history(history)
        
    @classmethod
    def get_history(cls):
        return cls._load_history()
        
    @classmethod
    def _load_history(cls):
        if os.path.exists(cls.FILE_PATH):
            try:
                with open(cls.FILE_PATH, 'r') as f:
                    return json.load(f)
            except Exception:
                return []
        return []
        
    @classmethod
    def _save_history(cls, history):
        try:
            with open(cls.FILE_PATH, 'w') as f:
                json.dump(history, f, indent=4)
        except Exception as e:
            print(f"Error saving report history: {e}")

class ReportHistoryUI(tk.Toplevel):
    """UI to display the report generation history."""
    
    def __init__(self, parent):
        super().__init__(parent)
        self.title("Report History")
        self.geometry("700x400")
        self.configure(bg=Config.COLORS["light"])
        self.transient(parent)
        
        self.setup_ui()
        self.load_data()
        
    def setup_ui(self):
        header = tk.Frame(self, bg=Config.COLORS["primary"], height=50)
        header.pack(fill="x")
        tk.Label(header, text="📄 Report Generation History", font=("Segoe UI", 14, "bold"), bg=Config.COLORS["primary"], fg="white").pack(pady=10)
        
        list_frame = tk.Frame(self, bg=Config.COLORS["white"], padx=10, pady=10)
        list_frame.pack(fill="both", expand=True, padx=10, pady=10)
        
        columns = ("Timestamp", "Type", "Filename", "Generated By", "Status")
        self.tree = ttk.Treeview(list_frame, columns=columns, show="headings")
        
        self.tree.heading("Timestamp", text="Date & Time")
        self.tree.heading("Type", text="Type")
        self.tree.heading("Filename", text="Filename")
        self.tree.heading("Generated By", text="Generated By")
        self.tree.heading("Status", text="Status")
        
        self.tree.column("Timestamp", width=130)
        self.tree.column("Type", width=70)
        self.tree.column("Filename", width=250)
        self.tree.column("Generated By", width=100)
        self.tree.column("Status", width=80)
        
        scrollbar = ttk.Scrollbar(list_frame, orient="vertical", command=self.tree.yview)
        self.tree.configure(yscrollcommand=scrollbar.set)
        
        self.tree.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")
        
        btn_frame = tk.Frame(self, bg=Config.COLORS["light"])
        btn_frame.pack(fill="x", pady=5)
        tk.Button(btn_frame, text="Close", font=("Segoe UI", 10), bg=Config.COLORS["gray"], fg="white", relief="flat", command=self.destroy).pack(pady=5)
        
    def load_data(self):
        for item in self.tree.get_children():
            self.tree.delete(item)
            
        history = ReportHistoryManager.get_history()
        for record in history:
            self.tree.insert("", "end", values=(
                record.get("timestamp", ""),
                record.get("type", ""),
                record.get("filename", ""),
                record.get("username", ""),
                record.get("status", "")
            ))
